development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: shared_id_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: shared_id_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: shared_id_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock